# Generated by Django 5.1.7 on 2025-03-28 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dessc',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 29)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
